[package]
name = "btspeak-keyboard-interceptor"
version = "0.1.0"
edition = "2024"

[dependencies]
evdev = { version = "0.13.1", features = ["tokio"] }
tokio = { version = "1.47.1", features = ["full"] }
